# Generated by Django 4.2.26 on 2025-11-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_seller_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['-listed_on']},
        ),
    ]
